#!/usr/bin/python
import maptools.minimap
import sys
import os
if __name__ == "__main__":
	argv = sys.argv
	if (len(argv)<3):
		print "Few argument. Use program as: addminimap [directory-path] [map-path]"
		exit(0)
	if not os.path.exists(argv[1]):
		print "Error path to directory. Directory does not exists"
		exit(0)
	if not os.path.exists(argv[2]):
		print "Error path to map. File does not exist"
		exit(0)
	
	maptools.minimap.minimap_create(argv[2],argv[1])