#!/usr/bin/python
import maptools.minimap
import sys
import os
if __name__ == "__main__":
	argv = sys.argv
	if (len(argv)<3):
		print "Few argument. Use program as: splitmap [map-path] [gpx-path] [utc-zone]"
		exit(0)
	if not os.path.exists(argv[1]):
		print "Error path to map. File does not exist"
		exit(0)
	if not os.path.exists(argv[2]):
		print "Error path to gpx file. File not exist"
		exit(0)
	if int(argv[3])>12 or int(argv[3])<-12:
		print "UTC zone must be between -12 and 12"
		exit(0)
	maptools.minimap.split_by_gpx(os.path.abspath(argv[1]),os.path.abspath(argv[2]),argv[3])
